INSERT INTO
RAITING_STARS (RAITING) VALUES ('NONE');

INSERT INTO
RAITING_STARS (RAITING) VALUES ('ONE_STAR');

INSERT INTO
RAITING_STARS (RAITING) VALUES ('TWO_STARS');

INSERT INTO
RAITING_STARS (RAITING) VALUES ('THREE_STARS');

INSERT INTO
RAITING_STARS (RAITING) VALUES ('FOUR_STARS');

INSERT INTO
RAITING_STARS (RAITING) VALUES ('FIVE_STARS');